import { createServerFn } from '@tanstack/react-start';
import { z } from 'zod';
import { requireSupabaseAuth } from '@/integrations/supabase/auth-middleware';
async function assertAdmin(context: { supabase: any; userId: string }) {
  const { data, error } = await context.supabase.from('user_roles').select('role').eq('user_id', context.userId).eq('role', 'admin').maybeSingle();
  if (error || !data) throw new Error('Administrator access required.');
}
export const getAdminData = createServerFn({ method: 'GET' }).middleware([requireSupabaseAuth]).handler(async ({ context }) => {
  await assertAdmin(context);
  const [applications, feedback, inquiries, courses, admins] = await Promise.all([
    context.supabase.from('applications').select('*,courses(title)').order('created_at',{ascending:false}),
    context.supabase.from('feedback').select('*').order('created_at',{ascending:false}),
    context.supabase.from('contact_inquiries').select('*').order('created_at',{ascending:false}),
    context.supabase.from('courses').select('*').order('created_at',{ascending:true}),
    context.supabase.from('admin_profiles').select('id,auth_user_id,email,created_at').order('created_at',{ascending:true}),
  ]);
  for(const item of [applications,feedback,inquiries,courses,admins]) if(item.error) throw new Error('Could not load administrator records.');
  return { applications:applications.data??[], feedback:feedback.data??[], inquiries:inquiries.data??[], courses:courses.data??[], admins:admins.data??[] };
});
const uuid=z.string().uuid();
export const updateApplication=createServerFn({method:'POST'}).middleware([requireSupabaseAuth]).inputValidator((input:unknown)=>z.object({id:uuid,status:z.enum(['New','Under Review','Accepted','Rejected']),admin_notes:z.string().max(2000)}).parse(input)).handler(async({data,context})=>{await assertAdmin(context);const {error}=await context.supabase.from('applications').update({status:data.status,admin_notes:data.admin_notes}).eq('id',data.id);if(error)throw new Error('Could not update application.');return {ok:true}});
export const deleteApplication=createServerFn({method:'POST'}).middleware([requireSupabaseAuth]).inputValidator((input:unknown)=>z.object({id:uuid}).parse(input)).handler(async({data,context})=>{await assertAdmin(context);const {error}=await context.supabase.from('applications').delete().eq('id',data.id);if(error)throw new Error('Could not delete application.');return {ok:true}});
export const updateFeedback=createServerFn({method:'POST'}).middleware([requireSupabaseAuth]).inputValidator((input:unknown)=>z.object({id:uuid,status:z.enum(['Unread','Read','Reviewed']),category:z.enum(['General Feedback','Course Content','Learning Experience','Website Experience','Suggestions','Other'])}).parse(input)).handler(async({data,context})=>{await assertAdmin(context);const {error}=await context.supabase.from('feedback').update({status:data.status,category:data.category}).eq('id',data.id);if(error)throw new Error('Could not update feedback.');return {ok:true}});
export const deleteFeedback=createServerFn({method:'POST'}).middleware([requireSupabaseAuth]).inputValidator((input:unknown)=>z.object({id:uuid}).parse(input)).handler(async({data,context})=>{await assertAdmin(context);const {error}=await context.supabase.from('feedback').delete().eq('id',data.id);if(error)throw new Error('Could not delete feedback.');return {ok:true}});
export const updateInquiry=createServerFn({method:'POST'}).middleware([requireSupabaseAuth]).inputValidator((input:unknown)=>z.object({id:uuid,status:z.enum(['New','Read','Resolved'])}).parse(input)).handler(async({data,context})=>{await assertAdmin(context);const {error}=await context.supabase.from('contact_inquiries').update({status:data.status}).eq('id',data.id);if(error)throw new Error('Could not update inquiry.');return {ok:true}});
export const deleteInquiry=createServerFn({method:'POST'}).middleware([requireSupabaseAuth]).inputValidator((input:unknown)=>z.object({id:uuid}).parse(input)).handler(async({data,context})=>{await assertAdmin(context);const {error}=await context.supabase.from('contact_inquiries').delete().eq('id',data.id);if(error)throw new Error('Could not delete inquiry.');return {ok:true}});
export const updateCourse=createServerFn({method:'POST'}).middleware([requireSupabaseAuth]).inputValidator((input:unknown)=>z.object({id:uuid,description:z.string().trim().min(15).max(2000),duration:z.string().trim().min(2).max(100),start_date:z.union([z.string().regex(/^\d{4}-\d{2}-\d{2}$/),z.literal('')]),learning_mode:z.string().trim().min(2).max(100),schedule:z.string().trim().min(2).max(100),weekly_hours:z.string().trim().min(2).max(100),tuition_kes:z.coerce.number().int().min(0),tuition_usd:z.coerce.number().int().min(0),is_active:z.boolean()}).parse(input)).handler(async({data,context})=>{await assertAdmin(context);const {error}=await context.supabase.from('courses').update({...data,start_date:data.start_date||null}).eq('id',data.id);if(error)throw new Error('Could not update course.');return {ok:true}});
export const addAdmin=createServerFn({method:'POST'}).middleware([requireSupabaseAuth]).inputValidator((input:unknown)=>z.object({email:z.string().trim().email().max(255)}).parse(input)).handler(async({data,context})=>{await assertAdmin(context);const {supabaseAdmin}=await import('@/integrations/supabase/client.server');const {data:users,error}=await supabaseAdmin.auth.admin.listUsers();if(error)throw new Error('Could not find account.');const user=users.users.find(u=>u.email?.toLowerCase()===data.email.toLowerCase());if(!user)throw new Error('That person must first create an account.');const {error:roleError}=await supabaseAdmin.from('user_roles').upsert({user_id:user.id,role:'admin'},{onConflict:'user_id'});if(roleError)throw new Error('Could not grant access.');const {error:profileError}=await supabaseAdmin.from('admin_profiles').upsert({auth_user_id:user.id,email:data.email},{onConflict:'auth_user_id'});if(profileError)throw new Error('Could not save administrator.');return {ok:true}});
export const removeAdmin=createServerFn({method:'POST'}).middleware([requireSupabaseAuth]).inputValidator((input:unknown)=>z.object({user_id:uuid}).parse(input)).handler(async({data,context})=>{await assertAdmin(context);if(data.user_id===context.userId)throw new Error('You cannot remove yourself.');const {supabaseAdmin}=await import('@/integrations/supabase/client.server');const {error}=await supabaseAdmin.from('user_roles').delete().eq('user_id',data.user_id).eq('role','admin');if(error)throw new Error('Could not remove administrator.');await supabaseAdmin.from('admin_profiles').delete().eq('auth_user_id',data.user_id);return {ok:true}});
