import { useEffect, useState, useRef } from 'react';
import { createFileRoute, Link } from '@tanstack/react-router';
import { ArrowRight, ArrowLeft, ArrowUpRight, Code2, ShieldCheck, Lightbulb, Users, BriefcaseBusiness, Laptop, Sparkles } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { CourseCard } from '@/components/course-card';
import { getCourses } from '@/lib/public.functions';
import { images } from '@/lib/site';
import hero from '@/assets/hero-academy.jpg';
export const Route = createFileRoute('/')({ loader: () => getCourses(), head: () => ({ meta: [{title:'Mzalendo Tech Hub | We Equip and Transform'},{name:'description',content:'Build practical skills in software engineering and cybersecurity with Mzalendo Tech Hub’s online courses.'},{property:'og:title',content:'Mzalendo Tech Hub | We Equip and Transform'},{property:'og:description',content:'Practical online training in web development, mobile app development, and cybersecurity.'},{property:'og:type',content:'website'},{name:'twitter:card',content:'summary_large_image'}] }), component: Home });
const features = [{icon:Code2,title:'Practical, Hands-On Training',text:'Learn by building projects that turn theory into real capability.'},{icon:ShieldCheck,title:'Industry-Relevant Skills',text:'Develop tools and techniques aligned with today’s technology landscape.'},{icon:Laptop,title:'Flexible Online Learning',text:'Grow your skills from wherever you are, alongside your daily commitments.'},{icon:Users,title:'Experienced Mentorship',text:'Get guidance and support as you navigate your learning journey.'},{icon:BriefcaseBusiness,title:'Career-Oriented Learning',text:'Build a foundation for the next step in your technology career.'},{icon:Lightbulb,title:'Innovation and Creativity',text:'Explore new ideas and learn to create meaningful solutions.'}];
function Home(){const courses=Route.useLoaderData();const [slide,setSlide]=useState(0);const touch=useRef(0);useEffect(()=>{if(courses.length<2)return;const id=window.setInterval(()=>setSlide(s=>(s+1)%courses.length),5000);return()=>clearInterval(id)},[courses.length]);const active=courses[slide];return <>
<section className="relative flex min-h-[640px] items-center overflow-hidden bg-navy text-primary-foreground max-sm:min-h-[620px]"><img src={hero} alt="Learners collaborating with laptops in a modern technology workspace" width={1536} height={1024} className="absolute inset-0 h-full w-full object-cover object-[65%_center]"/><div className="hero-shade absolute inset-0"/><div className="section-wrap relative z-10 py-20"><div className="max-w-2xl"><div className="mb-5 flex items-center gap-3 text-xs font-bold uppercase tracking-widest text-teal"><span className="h-px w-10 bg-orange"/>Learn. Build. Transform.</div><h1 className="max-w-2xl text-5xl leading-[1.08] font-bold sm:text-6xl lg:text-7xl">Welcome to Mzalendo Tech Hub</h1><p className="mt-5 text-xl font-semibold text-teal sm:text-2xl">We Equip and Transform</p><p className="mt-5 max-w-xl text-base leading-8 opacity-90">Unlock your potential with practical technology training in Software Engineering and Cybersecurity. Gain the skills, confidence, and knowledge to build innovative solutions and shape the digital future.</p><div className="mt-9 flex flex-wrap gap-3"><Button asChild variant="accent" size="lg" className="h-12"><Link to="/courses">Explore Our Courses <ArrowRight/></Link></Button><Button asChild variant="outline" size="lg" className="h-12 border-primary-foreground/60 bg-transparent text-primary-foreground hover:bg-primary-foreground/10"><Link to="/apply" search={{course:undefined}}>Apply Now</Link></Button></div></div></div><div className="absolute bottom-0 left-0 h-1 w-1/3 bg-orange"/><div className="absolute bottom-0 left-1/3 h-1 w-2/3 bg-teal"/></section>
<section className="section-space bg-surface"><div className="section-wrap"><div className="mb-8 flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-widest text-teal">Find your direction</p><h2 className="mt-3 text-3xl font-bold text-primary sm:text-4xl">A path for every ambition.</h2></div><span className="text-sm text-muted-foreground">01 / 03 · Featured programmes</span></div>{active&&<div className="grid overflow-hidden rounded-lg bg-navy text-primary-foreground md:grid-cols-2" onTouchStart={e=>touch.current=e.touches[0]?.clientX ?? 0} onTouchEnd={e=>{const d=(e.changedTouches[0]?.clientX ?? 0)-touch.current;if(Math.abs(d)>40)setSlide((s)=>(s+(d<0?1:courses.length-1))%courses.length)}}><img key={active.slug} src={images[active.slug]} alt={active.title} width={1024} height={768} loading="lazy" className="aspect-[1.5] h-full w-full object-cover"/><div className="flex flex-col justify-center p-7 sm:p-12"><span className="text-xs font-bold uppercase tracking-widest text-teal">Featured course · 0{slide+1}</span><h3 className="mt-4 text-3xl font-bold sm:text-4xl">{active.title}</h3><p className="mt-5 max-w-md leading-8 opacity-80">{active.description}</p><div className="mt-8"><Button asChild variant="accent" size="lg"><Link to="/courses/$slug" params={{slug:active.slug}}>{active.slug==='cybersecurity'?'Explore Cybersecurity':active.slug.endsWith('web')?'Explore Web Development':'Explore Mobile App Development'} <ArrowUpRight/></Link></Button></div></div></div>}<div className="mt-5 flex items-center justify-between"><div className="flex gap-2">{courses.map((c,i)=><Button key={c.id} variant="ghost" size="icon" className="size-7" aria-label={`Show slide ${i+1}`} onClick={()=>setSlide(i)}><span className={`size-2 rounded-full ${i===slide?'bg-primary':'bg-border'}`}/></Button>)}</div><div className="flex gap-2"><Button variant="outline" size="icon" aria-label="Previous slide" onClick={()=>setSlide(s=>(s+courses.length-1)%courses.length)}><ArrowLeft/></Button><Button variant="outline" size="icon" aria-label="Next slide" onClick={()=>setSlide(s=>(s+1)%courses.length)}><ArrowRight/></Button></div></div></div></section>
<section className="section-space"><div className="section-wrap"><div className="mb-10 flex flex-wrap items-end justify-between gap-6"><div><p className="text-xs font-bold uppercase tracking-widest text-teal">Build what’s next</p><h2 className="mt-3 text-3xl font-bold text-primary sm:text-4xl">Explore Our Courses</h2><p className="mt-3 text-muted-foreground">Choose your path, develop practical skills, and take the next step towards your technology career.</p></div><Button asChild variant="outline"><Link to="/courses">All courses <ArrowRight/></Link></Button></div><div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3">{courses.map(c=><CourseCard key={c.id} course={c}/>)}</div></div></section>
<section className="section-space bg-surface"><div className="section-wrap"><p className="text-xs font-bold uppercase tracking-widest text-teal">The Mzalendo difference</p><h2 className="mt-3 text-3xl font-bold text-primary sm:text-4xl">Why Choose Mzalendo Tech Hub?</h2><div className="mt-10 grid gap-x-10 gap-y-9 sm:grid-cols-2 lg:grid-cols-3">{features.map(({icon:Icon,title,text})=><div key={title} className="border-l-2 border-teal pl-5"><Icon className="mb-4 size-7 text-primary"/><h3 className="text-lg font-bold text-primary">{title}</h3><p className="mt-2 text-sm leading-7 text-muted-foreground">{text}</p></div>)}</div></div></section>
<section className="brand-gradient section-space text-primary-foreground"><div className="section-wrap flex flex-wrap items-center justify-between gap-8"><div className="max-w-2xl"><Sparkles className="mb-5 size-8 text-orange"/><h2 className="text-3xl font-bold sm:text-5xl">Your Future in Technology Starts Here</h2><p className="mt-5 leading-8 opacity-90">Take the first step towards transforming your skills and unlocking new opportunities in the technology industry.</p></div><Button asChild variant="accent" size="lg" className="h-12"><Link to="/courses">Explore Our Courses <ArrowRight/></Link></Button></div></section>
<section className="section-space"><div className="section-wrap flex flex-wrap items-center justify-between gap-6"><div><p className="text-xs font-bold uppercase tracking-widest text-teal">We’re listening</p><h2 className="mt-3 text-3xl font-bold text-primary">Your Feedback Matters</h2><p className="mt-3 text-muted-foreground">Help us improve our training experience and services. Share your thoughts, suggestions, or concerns with us.</p></div><Button asChild variant="teal" size="lg"><Link to="/feedback">Share feedback <ArrowRight/></Link></Button></div></section></>}
